### ISSUE TITLE
Sollevamento di un livello del contenuto della cartella "Webapp"

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/microservizi-webapp#17]
Sposterei su di un livello l'intero contenuto della cartella "webapp" rimuovendo la stessa quando vuota.

Come discusso anche con @pierobonluca01

**Comment by pierobonluca01** [comment]
Ricordarsi di cambiare la directory in [ghpage,yml](https://github.com/SWEasabi/microservizi-webapp/blob/main/.github/workflows/ghpage.yml)
