### ISSUE TITLE
struttura webapp e funzionalità richieste

### ISSUE THREAD

**Issue by SamuelPeron** [SWEasabi/microservizi-webapp#2]
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #9
- [x] #10
- [x] #11

**Comment by Giorgio-Zarantonello** [comment]
#3 #4 #5 done , see [e2455a7](https://github.com/SWEasabi/microservizi-webapp/pull/7/commits/e2455a7903e91d350af78b12eaa73837f5c592da)
